export const seedData = [
  {
    optionId: 1,
    name: "Hospital",
    inputType: "dropdown",
    callFieldName: "hospital",
    options: [
      {
        id: 1,
        name: "Erlanger Main",
      },
      {
        id: 2,
        name: "Erlanger East",
      },
      {
        id: 3,
        name: "Erlanger North",
      },
      {
        id: 4,
        name: "Erlanger Children's",
      },
      {
        id: 5,
        name: "Erlanger Bledsoe",
      },
      {
        id: 6,
        name: "Siskin",
      },
    ],
  },
  {
    optionId: 2,
    name: "Medical Record Number",
    inputType: "number",
    callFieldName: "mrn",
  },
  {
    optionId: 3,
    name: "Provider",
    inputType: "text",
    callFieldName: "provider",
  },
  {
    optionId: 4,
    name: "MD Order Changed?",
    inputType: "confirm",
    callFieldName: "orderChange",
    options: [
      {
        id: 1,
        name: "PICC changed to ML",
      },
      {
        id: 2,
        name: "PICC changed to IV",
      },
      {
        id: 3,
        name: "ML changed to IV",
      },
      {
        id: 4,
        name: "ML changed to PICC",
      },
      {
        id: 5,
        name: "IV changed to PICC",
      },
      {
        id: 6,
        name: "IV changed to ML",
      },
    ],
  },
  {
    optionId: 5,
    name: "Consultation",
    inputType: "checkbox",
    callFieldName: "wasConsultation",
  },
  {
    optionId: 6,
    name: "Call Needs",
    inputType: "dropdown",
    callFieldName: "callNeeds",
    options: [
      {
        seq: 1,
        id: 1,
        name: "New IV",
      },
      {
        seq: 2,
        id: 2,
        name: "Lab Draw",
      },
      {
        seq: 3,
        id: 3,
        name: "Labs + IV",
      },
      {
        seq: 4,
        id: 4,
        name: "Blood Culture",
      },
      {
        seq: 5,
        id: 5,
        name: "PICC Line",
      },
      {
        seq: 6,
        id: 6,
        name: "ML",
      },
      {
        seq: 7,
        id: 7,
        name: "Port Access",
      },
      {
        seq: 8,
        id: 8,
        name: "Port De-Access",
      },
      {
        seq: 9,
        id: 9,
        name: "Troubleshoot",
      },
      {
        seq: 10,
        id: 10,
        name: "Dressing Change",
      },
      {
        seq: 11,
        id: 11,
        name: "DC PICC",
      },
      {
        seq: 12,
        id: 12,
        name: "Line Check",
      },
      {
        seq: 13,
        id: 13,
        name: "Labs + BC",
      },
      {
        seq: 1000,
        id: 14,
        name: "Custom",
      },
      {
        seq: 14,
        id: 15,
        name: "IV x 2",
      },
      {
        seq: 15,
        id: 16,
        name: "Type & Cross",
      },
      {
        seq: 16,
        id: 17,
        name: "Start IV + DC line",
      },
    ],
  },
  {
    optionId: 7,
    name: "Status Codes",
    inputType: "dropdown",
    callFieldName: "status",
    options: [
      {
        id: 1,
        name: "Normal",
      },
      {
        id: 2,
        name: "Stat",
      },
      {
        id: 3,
        name: "On Hold",
      },
    ],
  },
];

exports.itemSeed = [
  {
    itemId: 1,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "Patient Refused",
    value: "Patient Refused",
    isCustom: false,
  },
  {
    itemId: 2,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "Size",
    value: "24g",
    isCustom: false,
  },
  {
    itemId: 3,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "Size",
    value: "22g",
    isCustom: false,
  },
  {
    itemId: 4,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "Size",
    value: "20g",
    isCustom: false,
  },
  {
    itemId: 5,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "Size",
    value: "18g",
    isCustom: false,
  },
  {
    itemId: 6,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "Care Type",
    value: "IV Flushed",
    isCustom: false,
  },
  {
    itemId: 7,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "Care Type",
    value: "Saline Locked",
    isCustom: false,
  },
  {
    itemId: 8,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "Care Type",
    value: "Dressing Changed",
    isCustom: false,
  },
  {
    itemId: 9,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "Care Type",
    value: "Dressing Reinforced",
    isCustom: false,
  },
  {
    itemId: 10,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "DC IV",
    value: "Inflitration",
    isCustom: false,
  },
  {
    itemId: 11,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "DC IV",
    value: "Phlebitis",
    isCustom: false,
  },
  {
    itemId: 12,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "DC IV",
    value: "PT Removal",
    isCustom: false,
  },
  {
    itemId: 13,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "DC IV",
    value: "Leaking",
    isCustom: false,
  },
  {
    itemId: 14,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "DC IV",
    value: "Painful",
    isCustom: false,
  },
  {
    itemId: 15,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "DC IV",
    value: "Per Protocol",
    isCustom: false,
  },
  {
    itemId: 16,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "Ultrasound",
    value: "US Used",
    isCustom: false,
  },
  {
    itemId: 17,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "Blood Drawn",
    value: "Blood Was Drawn",
    isCustom: false,
  },
  {
    itemId: 18,
    procedureName: "Lab Draw",
    procedureId: 2,
    groupName: "Patient Refused",
    value: "Patient Refused",
    isCustom: false,
  },
  {
    itemId: 19,
    procedureName: "Lab Draw",
    procedureId: 2,
    groupName: "Draw Type",
    value: "From IV",
    isCustom: false,
  },
  {
    itemId: 20,
    procedureName: "Lab Draw",
    procedureId: 2,
    groupName: "Draw Type",
    value: "Labs Only",
    isCustom: false,
  },
  {
    itemId: 21,
    procedureName: "Lab Draw",
    procedureId: 2,
    groupName: "Ultrasound",
    value: "US Used",
    isCustom: false,
  },
  {
    itemId: 22,
    procedureName: "Blood Culture",
    procedureId: 3,
    groupName: "Patient Refused",
    value: "Patient Refused",
    isCustom: false,
  },
  {
    itemId: 23,
    procedureName: "Blood Culture",
    procedureId: 3,
    groupName: "From",
    value: "PICC",
    isCustom: false,
  },
  {
    itemId: 24,
    procedureName: "Blood Culture",
    procedureId: 3,
    groupName: "From",
    value: "ML",
    isCustom: false,
  },
  {
    itemId: 25,
    procedureName: "Blood Culture",
    procedureId: 3,
    groupName: "From",
    value: "Central Line",
    isCustom: false,
  },
  {
    itemId: 26,
    procedureName: "Blood Culture",
    procedureId: 3,
    groupName: "From",
    value: "IV",
    isCustom: false,
  },
  {
    itemId: 27,
    procedureName: "Blood Culture",
    procedureId: 3,
    groupName: "From",
    value: "Peripheral Stick x 1",
    isCustom: false,
  },
  {
    itemId: 28,
    procedureName: "Blood Culture",
    procedureId: 3,
    groupName: "From",
    value: "Peripheral Stick x 2",
    isCustom: false,
  },
  {
    itemId: 29,
    procedureName: "Blood Culture",
    procedureId: 3,
    groupName: "Ultrasound",
    value: "US Used",
    isCustom: false,
  },
  {
    itemId: 30,
    procedureName: "Port-A-Cath",
    procedureId: 4,
    groupName: "Type",
    value: "Access",
    isCustom: false,
  },
  {
    itemId: 31,
    procedureName: "Port-A-Cath",
    procedureId: 4,
    groupName: "Type",
    value: "De-Access",
    isCustom: false,
  },
  {
    itemId: 32,
    procedureName: "PICC Line",
    procedureId: 5,
    groupName: "Removal",
    value: "Therapy Complete",
    isCustom: false,
  },
  {
    itemId: 33,
    procedureName: "PICC Line",
    procedureId: 5,
    groupName: "Removal",
    value: "Discharge",
    isCustom: false,
  },
  {
    itemId: 34,
    procedureName: "PICC Line",
    procedureId: 5,
    groupName: "Removal",
    value: "Clotted",
    isCustom: false,
  },
  {
    itemId: 35,
    procedureName: "PICC Line",
    procedureId: 5,
    groupName: "Removal",
    value: "Contaminated",
    isCustom: false,
  },
  {
    itemId: 36,
    procedureName: "PICC Line",
    procedureId: 5,
    groupName: "Removal",
    value: "PT Removal",
    isCustom: false,
  },
  {
    itemId: 37,
    procedureName: "Dressing Change",
    procedureId: 6,
    groupName: "What",
    value: "PICC",
    isCustom: false,
  },
  {
    itemId: 38,
    procedureName: "Dressing Change",
    procedureId: 6,
    groupName: "What",
    value: "Port-A-Cath",
    isCustom: false,
  },
  {
    itemId: 39,
    procedureName: "Dressing Change",
    procedureId: 6,
    groupName: "What",
    value: "Central Line",
    isCustom: false,
  },
  {
    itemId: 40,
    procedureName: "Dressing Change",
    procedureId: 6,
    groupName: "What",
    value: "ML",
    isCustom: false,
  },
  {
    itemId: 41,
    procedureName: "Dressing Change",
    procedureId: 6,
    groupName: "Why",
    value: "Per Protocol",
    isCustom: false,
  },
  {
    itemId: 42,
    procedureName: "Dressing Change",
    procedureId: 6,
    groupName: "Why",
    value: "Bleeding",
    isCustom: false,
  },
  {
    itemId: 43,
    procedureName: "Dressing Change",
    procedureId: 6,
    groupName: "Why",
    value: "Site Assessment",
    isCustom: false,
  },
  {
    itemId: 44,
    procedureName: "Dressing Change",
    procedureId: 6,
    groupName: "Why",
    value: "Dressing Compromised",
    isCustom: false,
  },
  {
    itemId: 45,
    procedureName: "Troubleshoot",
    procedureId: 7,
    groupName: "What",
    value: "ML",
    isCustom: false,
  },
  {
    itemId: 46,
    procedureName: "Troubleshoot",
    procedureId: 7,
    groupName: "What",
    value: "PICC",
    isCustom: false,
  },
  {
    itemId: 47,
    procedureName: "Troubleshoot",
    procedureId: 7,
    groupName: "What",
    value: "Central Line",
    isCustom: false,
  },
  {
    itemId: 48,
    procedureName: "Troubleshoot",
    procedureId: 7,
    groupName: "What",
    value: "Port",
    isCustom: false,
  },
  {
    itemId: 49,
    procedureName: "Troubleshoot",
    procedureId: 7,
    groupName: "What",
    value: "IV",
    isCustom: false,
  },
  {
    itemId: 50,
    procedureName: "Troubleshoot",
    procedureId: 7,
    groupName: "Intervention",
    value: "Power Flush",
    isCustom: false,
  },
  {
    itemId: 51,
    procedureName: "Troubleshoot",
    procedureId: 7,
    groupName: "Intervention",
    value: "Clave Change",
    isCustom: false,
  },
  {
    itemId: 52,
    procedureName: "Troubleshoot",
    procedureId: 7,
    groupName: "Intervention",
    value: "Recommend DC",
    isCustom: false,
  },
  {
    itemId: 53,
    procedureName: "Troubleshoot",
    procedureId: 7,
    groupName: "Intervention",
    value: "Line Retracted",
    isCustom: false,
  },
  {
    itemId: 54,
    procedureName: "Troubleshoot",
    procedureId: 7,
    groupName: "Intervention",
    value: "Repositioned",
    isCustom: false,
  },
  {
    itemId: 55,
    procedureName: "Troubleshoot",
    procedureId: 7,
    groupName: "Cathflo",
    value: "PAC: Initiated",
    isCustom: false,
  },
  {
    itemId: 56,
    procedureName: "Troubleshoot",
    procedureId: 7,
    groupName: "Cathflo",
    value: "PAC: Completed",
    isCustom: false,
  },
  {
    itemId: 57,
    procedureName: "Insertion Procedure",
    procedureId: 8,
    groupName: "Patient Refused",
    value: "Patient Refused",
    isCustom: false,
  },
  {
    itemId: 58,
    procedureName: "Insertion Procedure",
    procedureId: 8,
    groupName: "Insertion Type",
    value: "SL PICC",
    isCustom: false,
  },
  {
    itemId: 59,
    procedureName: "Insertion Procedure",
    procedureId: 8,
    groupName: "Insertion Type",
    value: "DL PICC",
    isCustom: false,
  },
  {
    itemId: 60,
    procedureName: "Insertion Procedure",
    procedureId: 8,
    groupName: "Insertion Type",
    value: "TL PICC",
    isCustom: false,
  },
  {
    itemId: 61,
    procedureName: "Insertion Procedure",
    procedureId: 8,
    groupName: "Insertion Type",
    value: "ML",
    isCustom: false,
  },
  {
    itemId: 62,
    procedureName: "Insertion Procedure",
    procedureId: 8,
    groupName: "Insertion Type",
    value: "PG",
    isCustom: false,
  },
  {
    itemId: 63,
    procedureName: "Insertion Procedure",
    procedureId: 8,
    groupName: "Vessel",
    value: "Basilic",
    isCustom: false,
  },
  {
    itemId: 64,
    procedureName: "Insertion Procedure",
    procedureId: 8,
    groupName: "Vessel",
    value: "Brachial",
    isCustom: false,
  },
  {
    itemId: 65,
    procedureName: "Insertion Procedure",
    procedureId: 8,
    groupName: "Vessel",
    value: "Cephalic",
    isCustom: false,
  },
  {
    itemId: 66,
    procedureName: "Insertion Procedure",
    procedureId: 8,
    groupName: "Vessel",
    value: "Internal Jugular",
    isCustom: false,
  },
  {
    itemId: 67,
    procedureName: "Insertion Procedure",
    procedureId: 8,
    groupName: "Vessel",
    value: "Femoral",
    isCustom: false,
  },
  {
    itemId: 68,
    procedureName: "Insertion Procedure",
    procedureId: 8,
    groupName: "Laterality",
    value: "Left",
    isCustom: false,
  },
  {
    itemId: 69,
    procedureName: "Insertion Procedure",
    procedureId: 8,
    groupName: "Laterality",
    value: "Right",
    isCustom: false,
  },
  {
    itemId: 70,
    procedureName: "Insertion Procedure",
    procedureId: 8,
    groupName: "Insertion Length",
    fieldName: "insertionLength",
    value: "in CM",
    isCustom: true,
    fieldAbbr: "Len",
    valuePrefix: "",
    valueSuffix: "cm",
  },
  {
    itemId: 71,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "Hospital Staff Obtained",
    value: "Hospital Staff Obtained",
    isCustom: false,
  },
  {
    itemId: 72,
    procedureName: "Lab Draw",
    procedureId: 2,
    groupName: "Hospital Staff Obtained",
    value: "Hospital Staff Obtained",
    isCustom: false,
  },
  {
    itemId: 73,
    procedureName: "Troubleshoot",
    procedureId: 7,
    groupName: "Cathflo",
    value: "PICC: Initiated",
    isCustom: false,
  },
  {
    itemId: 74,
    procedureName: "Troubleshoot",
    procedureId: 7,
    groupName: "Cathflo",
    value: "PICC: Completed",
    isCustom: false,
  },
  {
    itemId: 75,
    procedureName: "Troubleshoot",
    procedureId: 7,
    groupName: "Cathflo",
    value: "CVL: Initiated",
    isCustom: false,
  },
  {
    itemId: 76,
    procedureName: "Troubleshoot",
    procedureId: 7,
    groupName: "Cathflo",
    value: "CVL: Completed",
    isCustom: false,
  },
  {
    itemId: 77,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "DC ML",
    value: "Inflitration",
    isCustom: false,
  },
  {
    itemId: 78,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "DC ML",
    value: "Phlebitis",
    isCustom: false,
  },
  {
    itemId: 79,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "DC ML",
    value: "PT Removal",
    isCustom: false,
  },
  {
    itemId: 80,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "DC ML",
    value: "Leaking",
    isCustom: false,
  },
  {
    itemId: 81,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "DC ML",
    value: "Painful",
    isCustom: false,
  },
  {
    itemId: 82,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "DC ML",
    value: "Per Protocol",
    isCustom: false,
  },
  {
    itemId: 83,
    procedureName: "Line Check",
    procedureId: 9,
    groupName: "What",
    value: "CVL",
    isCustom: false,
  },
  {
    itemId: 84,
    procedureName: "Line Check",
    procedureId: 9,
    groupName: "What",
    value: "PICC",
    isCustom: false,
  },
  {
    itemId: 85,
    procedureName: "Line Check",
    procedureId: 9,
    groupName: "What",
    value: "IV",
    isCustom: false,
  },
  {
    itemId: 86,
    procedureName: "Line Check",
    procedureId: 9,
    groupName: "What",
    value: "ML",
    isCustom: false,
  },
  {
    itemId: 87,
    procedureName: "Line Check",
    procedureId: 9,
    groupName: "What",
    value: "PG",
    isCustom: false,
  },
  {
    itemId: 88,
    procedureName: "Line Check",
    procedureId: 9,
    groupName: "What",
    value: "PORT",
    isCustom: false,
  },
  {
    itemId: 89,
    procedureName: "Lab Draw",
    procedureId: 9,
    groupName: "Draw Type",
    value: "Port-A-Cath",
    isCustom: false,
  },
  {
    itemId: 90,
    procedureName: "Insertion Procedure",
    procedureId: 8,
    groupName: "Insertion Type",
    value: "CVL",
    isCustom: false,
  },
  {
    itemId: 91,
    procedureName: "Lab Draw",
    procedureId: 2,
    groupName: "Draw Type",
    value: "From PICC",
    isCustom: false,
  },
  {
    itemId: 92,
    procedureName: "Lab Draw",
    procedureId: 2,
    groupName: "Draw Type",
    value: "From ML",
    isCustom: false,
  },
  {
    itemId: 93,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "Patient Refused",
    value: "Patient Refused",
    isCustom: false,
  },
  {
    itemId: 94,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "Size",
    value: "24g",
    isCustom: false,
  },
  {
    itemId: 95,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "Size",
    value: "22g",
    isCustom: false,
  },
  {
    itemId: 96,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "Size",
    value: "20g",
    isCustom: false,
  },
  {
    itemId: 97,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "Size",
    value: "18g",
    isCustom: false,
  },
  {
    itemId: 98,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "Care Type",
    value: "IV Flushed",
    isCustom: false,
  },
  {
    itemId: 99,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "Care Type",
    value: "Saline Locked",
    isCustom: false,
  },
  {
    itemId: 100,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "Care Type",
    value: "Dressing Changed",
    isCustom: false,
  },
  {
    itemId: 101,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "Care Type",
    value: "Dressing Reinforced",
    isCustom: false,
  },
  {
    itemId: 102,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "DC IV",
    value: "Inflitration",
    isCustom: false,
  },
  {
    itemId: 103,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "DC IV",
    value: "Phlebitis",
    isCustom: false,
  },
  {
    itemId: 104,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "DC IV",
    value: "PT Removal",
    isCustom: false,
  },
  {
    itemId: 105,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "DC IV",
    value: "Leaking",
    isCustom: false,
  },
  {
    itemId: 106,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "DC IV",
    value: "Painful",
    isCustom: false,
  },
  {
    itemId: 107,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "DC IV",
    value: "Per Protocol",
    isCustom: false,
  },
  {
    itemId: 108,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "Ultrasound",
    value: "US Used",
    isCustom: false,
  },
  {
    itemId: 109,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "Blood Drawn",
    value: "Blood Was Drawn",
    isCustom: false,
  },
  {
    itemId: 110,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "Hospital Staff Obtained",
    value: "Hospital Staff Obtained",
    isCustom: false,
  },
  {
    itemId: 111,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "DC ML",
    value: "Inflitration",
    isCustom: false,
  },
  {
    itemId: 112,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "DC ML",
    value: "Phlebitis",
    isCustom: false,
  },
  {
    itemId: 113,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "DC ML",
    value: "PT Removal",
    isCustom: false,
  },
  {
    itemId: 114,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "DC ML",
    value: "Leaking",
    isCustom: false,
  },
  {
    itemId: 115,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "DC ML",
    value: "Painful",
    isCustom: false,
  },
  {
    itemId: 116,
    procedureName: "PIV",
    procedureId: 1,
    groupName: "DC ML",
    value: "Per Protocol",
    isCustom: false,
  },
  {
    itemId: 117,
    procedureName: "Dressing Change",
    procedureId: 6,
    groupName: "What",
    value: "PG",
    isCustom: false,
  },
];

exports.procedureSeed = [
  {
    procedureId: 1,
    name: "PIV",
    seq: 1,
    groups: [
      {
        seq: 1,
        groupName: "Patient Refused",
        inputType: "checkbox",
        hideHeader: true,
        groupItems: [1],
      },
      {
        seq: 2,
        groupName: "Ultrasound",
        inputType: "checkbox",
        hideHeader: true,
        groupItems: [16],
      },
      {
        seq: 3,
        groupName: "Blood Drawn",
        inputType: "checkbox",
        hideHeader: true,
        groupItems: [17],
      },
      {
        seq: 4,
        groupName: "Size",
        inputType: "radio",
        groupItems: [2, 3, 4, 5],
      },
      {
        seq: 5,
        groupName: "Care Type",
        inputType: "checkbox",
        groupItems: [6, 7, 8, 9],
      },
      {
        seq: 6,
        groupName: "DC IV",
        inputType: "checkbox",
        groupItems: [10, 11, 12, 13, 14, 15],
      },
      {
        seq: 7,
        groupName: "DC ML",
        inputType: "checkbox",
        groupItems: [77, 78, 79, 80, 81, 82],
      },
      {
        seq: 8,
        groupName: "Hospital Staff Obtained",
        inputType: "checkbox",
        groupItems: [71],
      },
    ],
  },
  {
    procedureId: 2,
    name: "Lab Draw",
    seq: 2,
    groups: [
      {
        seq: 1,
        groupName: "Patient Refused",
        inputType: "checkbox",
        hideHeader: true,
        groupItems: [18],
      },
      {
        seq: 2,
        groupName: "Draw Type",
        inputType: "radio",
        groupItems: [19, 20, 89, 91, 92],
      },
      {
        seq: 3,
        groupName: "Ultrasound",
        inputType: "checkbox",
        groupItems: [21],
      },
      {
        seq: 4,
        groupName: "Hospital Staff Obtained",
        inputType: "checkbox",
        groupItems: [72],
      },
    ],
  },
  {
    procedureId: 3,
    name: "Blood Culture",
    seq: 3,
    groups: [
      {
        seq: 1,
        groupName: "Patient Refused",
        inputType: "checkbox",
        hideHeader: true,
        groupItems: [22],
      },
      {
        seq: 2,
        groupName: "From",
        inputType: "checkbox",
        groupItems: [23, 24, 25, 26, 27, 28],
      },
      {
        seq: 3,
        groupName: "Ultrasound",
        inputType: "checkbox",
        groupItems: [29],
      },
    ],
  },
  {
    procedureId: 4,
    name: "Port-A-Cath",
    seq: 4,
    groups: [
      {
        seq: 1,
        groupName: "Type",
        hideHeader: true,
        inputType: "checkbox",
        groupItems: [30, 31],
      },
    ],
  },
  {
    procedureId: 5,
    name: "PICC Line",
    seq: 5,
    groups: [
      {
        seq: 1,
        groupName: "Removal",
        inputType: "radio",
        groupItems: [32, 33, 34, 35, 36],
      },
    ],
  },
  {
    procedureId: 6,
    name: "Dressing Change",
    seq: 6,
    groups: [
      {
        seq: 1,
        groupName: "What",
        inputType: "radio",
        groupItems: [37, 38, 39, 40, 117],
      },
      {
        seq: 2,
        groupName: "Why",
        inputType: "radio",
        groupItems: [41, 42, 43, 44],
      },
    ],
  },
  {
    procedureId: 7,
    name: "Troubleshoot",
    seq: 7,
    groups: [
      {
        seq: 1,
        groupName: "What",
        inputType: "radio",
        groupItems: [45, 46, 47, 48, 49],
      },
      {
        seq: 2,
        groupName: "Intervention",
        inputType: "checkbox",
        groupItems: [50, 51, 52, 53, 54],
      },
      {
        seq: 3,
        groupName: "Cathflo",
        inputType: "checkbox",
        hideHeader: true,
        hideGroup: true,
        groupItems: [55, 56, 73, 74, 75, 76],
      },
    ],
  },
  {
    procedureId: 8,
    name: "Insertion Procedure",
    seq: 8,
    groups: [
      {
        seq: 1,
        groupName: "Patient Refused",
        inputType: "checkbox",
        hideHeader: true,
        groupItems: [57],
      },
      {
        seq: 2,
        groupName: "Insertion Type",
        inputType: "radio",
        groupItems: [58, 59, 60, 61, 62, 90],
      },
      {
        seq: 3,
        groupName: "Vessel",
        inputType: "radio",
        groupItems: [63, 64, 65, 66, 67],
      },
      {
        seq: 4,
        groupName: "Laterality",
        inputType: "radio",
        groupItems: [68, 69],
      },
      {
        seq: 5,
        groupName: "Insertion Length",
        fieldName: "insertionLength",
        inputType: "number",
        groupItems: [70],
      },
    ],
  },
  {
    procedureId: 9,
    name: "Line Check",
    seq: 2.1,
    groups: [
      {
        seq: 1,
        groupName: "What",
        inputType: "checkbox",
        hideHeader: true,
        groupItems: [83, 84, 85, 86, 87, 88],
      },
    ],
  },
  {
    procedureId: 10,
    name: "PIV (2nd)",
    seq: 1.1,
    groups: [
      {
        seq: 1,
        groupName: "Patient Refused",
        inputType: "checkbox",
        hideHeader: true,
        groupItems: [93],
      },
      {
        seq: 2,
        groupName: "Ultrasound",
        inputType: "checkbox",
        hideHeader: true,
        groupItems: [108],
      },
      {
        seq: 3,
        groupName: "Blood Drawn",
        inputType: "checkbox",
        hideHeader: true,
        groupItems: [109],
      },
      {
        seq: 4,
        groupName: "Size",
        inputType: "radio",
        groupItems: [94, 95, 96, 97],
      },
      {
        seq: 5,
        groupName: "Care Type",
        inputType: "checkbox",
        groupItems: [98, 99, 100, 101],
      },
      {
        seq: 6,
        groupName: "DC IV",
        inputType: "checkbox",
        groupItems: [102, 103, 104, 105, 106, 107],
      },
      {
        seq: 7,
        groupName: "DC ML",
        inputType: "checkbox",
        groupItems: [111, 112, 113, 114, 115, 116],
      },
      {
        seq: 8,
        groupName: "Hospital Staff Obtained",
        inputType: "checkbox",
        groupItems: [110],
      },
    ],
  },
];
